### ISSUE TITLE
Stablize docker for deploying on windows environments

### ISSUE THREAD

**Issue by SirPolaris** [Citizen-Group/Open311#78]
**Part of:** Development / Maint
**Prio:** Med High

As part of our ability to develop, we need to ensure that Docker can be deployed all environments. 

**Expected results:** 
- [ ] Application starts though Docker on windows.

**Comment by SirPolaris** [comment]
Note to self:
80% done. Could not validate. Just fast exit codes.
Docker runs fine on windows and the internal code has been ported over to a OS neutral flavour. 
When @DenisCarriere finishes with his Docker modifications, I'll close this PR. 
Need to debug.

**Comment by DenisCarriere** [comment]
Try to use the Docker-Compose approach, I was able to publish it to Heroku with "relative" ease and deploy it locally.
https://shrouded-retreat-98626.herokuapp.com/
https://github.com/YOWCT/pothole_webserver/issues/3

**Comment by SirPolaris** [comment]
I am looking forwarde to seeing Docker handle this nicely. As you are comitting to a remote repo, I have to wait for you to finish your code and port it. There was some issues on my end, with NPM Start in Docker vs on my local machine.

**Comment by SirPolaris** [comment]
Closed with many thanks to @DenisCarriere
